// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axrpaixwqixekaruouep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cnBhaXh3cWl4ZWthcnVvdWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTc0MTEsImV4cCI6MjA1MTQ5MzQxMX0.u90buDaYjry1rf43c7ja6HY3kddzfd2tHUrAOyisN5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);